nelmio_api_doc:
    documentation:
        info:
            title: Tasks Manager
            description: Tasks Manager
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
    models:
        names:
            - { alias: Task, type: App\Entity\Task }
            - { alias: Task Details, type: App\Entity\Task, groups: [details] }
